// packages/mascot/src/react/mascot-antenna.tsx
import {type ReactElement, useRef} from 'react'
import {type ClaimToken, useMascotContext} from './mascot-context.js'
import {MascotLayer} from './mascot-layer.js'
import type {MascotFollowPartProps} from './mascot-props.js'
import {useIsomorphicLayoutEffect} from './use-layout-effect.js'

export function MascotAntenna({follow, ...rest}: MascotFollowPartProps): ReactElement {
  const {claimPart} = useMascotContext()
  const token = useRef<ClaimToken>({}).current
  useIsomorphicLayoutEffect(() => claimPart('antenna', token, follow), [claimPart, token, follow])
  return <MascotLayer layer="antenna" {...rest} />
}

// packages/mascot/src/solid/mascot-antenna.tsx
import {type JSX, splitProps} from 'solid-js'
import {useMascotContext} from './mascot-context.js'
import {MascotLayer} from './mascot-layer.js'
import type {MascotFollowPartProps} from './mascot-props.js'

export function MascotAntenna(props: MascotFollowPartProps): JSX.Element {
  const context = useMascotContext()
  const [local, rest] = splitProps(props, ['follow'])
  context.claimPart('antenna', local)
  return <MascotLayer layer="antenna" {...rest} />
}
