// packages/mascot/src/react/mascot-layer.tsx
import {type ReactElement, useMemo, useRef} from 'react'
import {type MascotPartName, useMascotContext} from './mascot-context.js'
import {composeRefs, type MascotLayerProps, mergeStyle} from './mascot-props.js'
import {useIsomorphicLayoutEffect} from './use-layout-effect.js'

export type MascotLayerHostProps = MascotLayerProps & {layer: MascotPartName; fallback?: boolean}

export function MascotLayer({layer, fallback, style, ref, ...rest}: MascotLayerHostProps): ReactElement {
  const {partProps, claimOf} = useMascotContext()
  const part = partProps(layer)
  const element = useRef<HTMLSpanElement | null>(null)
  const setElement = useMemo(() => composeRefs(element, ref), [ref])

  useIsomorphicLayoutEffect(() => {
    const node = element.current
    if (node === null) return
    if (fallback === true && claimOf(layer) !== undefined) return
    part.ref(node)
    return () => part.release(node)
  }, [claimOf, fallback, layer, part])

  return (
    <span
      aria-hidden="true"
      {...rest}
      data-scope="mascot"
      data-part={layer}
      style={mergeStyle(part.style, style, true)}
      ref={setElement}
    />
  )
}

// packages/mascot/src/solid/mascot-layer.tsx
import {type JSX, onCleanup, onMount, splitProps} from 'solid-js'
import {Dynamic} from 'solid-js/web'
import {type MascotPartName, useMascotContext} from './mascot-context.js'
import {composeRefs, type MascotLayerProps, mergeStyle} from './mascot-props.js'

export type MascotLayerHostProps = MascotLayerProps & {layer: MascotPartName}

export function MascotLayer(props: MascotLayerHostProps): JSX.Element {
  const context = useMascotContext()
  const [local, rest] = splitProps(props, ['layer', 'style', 'ref'])
  const layer = () => context.partProps(local.layer)
  let element: HTMLSpanElement | undefined
  onMount(() => {
    if (element !== undefined) layer().ref(element)
  })
  onCleanup(() => {
    if (element !== undefined) layer().release(element)
  })
  return (
    <Dynamic
      component="span"
      aria-hidden="true"
      {...rest}
      data-scope="mascot"
      data-part={local.layer}
      style={mergeStyle(layer().style, local.style, true)}
      ref={composeRefs((node) => {
        element = node
      }, local.ref)}
    />
  )
}
