// packages/mascot/src/react/mascot-head.tsx
import {type ReactElement, useRef} from 'react'
import {type ClaimToken, useMascotContext} from './mascot-context.js'
import {MascotLayer} from './mascot-layer.js'
import type {MascotLayerProps} from './mascot-props.js'
import {useIsomorphicLayoutEffect} from './use-layout-effect.js'

export function MascotHead(props: MascotLayerProps): ReactElement {
  const {claimPart} = useMascotContext()
  const token = useRef<ClaimToken>({}).current
  useIsomorphicLayoutEffect(() => claimPart('head', token, undefined), [claimPart, token])
  return <MascotLayer layer="head" {...props} />
}

// packages/mascot/src/solid/mascot-head.tsx
import type {JSX} from 'solid-js'
import {useMascotContext} from './mascot-context.js'
import {MascotLayer} from './mascot-layer.js'
import type {MascotLayerProps} from './mascot-props.js'

export function MascotHead(props: MascotLayerProps): JSX.Element {
  const context = useMascotContext()
  context.claimPart('head')
  return <MascotLayer layer="head" {...props} />
}
